# Getting format from ansible network modules documentation(ios)
---
- name: Create Loopbacks on device
  hosts: switches
  connection: local
  tasks:
    - name: Create loopback shell
      with_items: "{{local_loopback}}"
      ios_interfaces:
        config:
          -name: "{{item.name}}"
           description: "{{item.desc}}"
           enabled: true
        state: replaced

    - name: Set new loopback configs
      with_items: "{{local_loopbacks}}"
      ios_l3_interfaces:
        config:
          -name: "{{item.name}}"
           ipv4:
            -address: "{{item.ip_address}}"
        state: replaced  